### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anasbousselham** [LukaSikic/subzy#10]
`lukasikic/subzy@v0.0.0-20210222175241-2686ade229f9/subzy.go:4:2: local import "./src" in non-local package
lukasikic/subzy@v0.0.0-20210222175241-2686ade229f9/src/process.go:5:2: cannot find package`

**Comment by shawalahmad123** [comment]
Same issue in mac book pro...

**Comment by himmat1005** [comment]
![image](https://user-images.githubusercontent.com/13080752/109639500-43928d00-7b75-11eb-9ef7-3e44bc66a8c5.png)

Same issue. Anyone able to get rid of it either on Windows or Kali Linux. Please let me know. Thanks.

**Comment by anasbousselham** [comment]
I think we need to downgrade Go to 1.14

**Comment by Dhruv-Pindawala** [comment]
Same is the case with me. When I opened the file subzy.go in VScode, I threw me an error.

The error was:
go: cannot find main module, but found .git/config in d:\Applications\subzy
	to create a module there, run:
	go mod init
Process exiting with code: 1 signal: false
Error killing process 8984: Error: Command failed: taskkill /pid 8984 /T /F
ERROR: The process "8984" not found.

**Comment by LukaSikic** [comment]
@anasbousselham I just pushed a code update, please try now and let me know if it works.

**Comment by Dhruv-Pindawala** [comment]
@LukaSikic now when I am trying to follow the installation process mentioned in readme.md (go get *, go install) and entering subzy in my terminal, it is showing subzy: command not found

**Comment by Dhruv-Pindawala** [comment]
@LukaSikic It is still not working. The problem is that there is no go.mod file. We just need to add that file. in subzy directory
