### ISSUE TITLE
Error processing: Process: Fingerprints: unexpected end of JSON input

### ISSUE THREAD

**Issue by pavanmsvs** [LukaSikic/subzy#20]
After installing I am getting this error

**Comment by icanseeyou0** [comment]
i am also geting this error

**Comment by Mouhannad963** [comment]
me too

**Comment by mokshitk** [comment]
I am also getting same error, Where is the author ???/

**Comment by karthikgohul** [comment]
Hii! Removing fingerprints.json is not working then manually set up the fingerprints.json file with https://github.com/LukaSikic/subzy/blob/master/src/fingerprints.json, It worked for me!

**Comment by jayantasharma** [comment]
It is not working for me, after removing and adding too

**Comment by karthikgohul** [comment]
I think the issue was resolved, Reinstall the subzy again

**Comment by BinaryXGhost** [comment]
Error: Process: Fingerprints: unexpected end of JSON input
facing this issue not matter what I do please help

**Comment by gauravlinux** [comment]
nope issue is still remain date - 21 aug 2024 worst tool no devloper support

**Comment by NSEcho** [comment]
@gauravlinux can you try it now with updated version

**Comment by gauravlinux** [comment]
Bro I downloaded the latest version

**Comment by NSEcho** [comment]
Run `go install -v github.com/PentestPad/subzy@latest` and let me know how it works

**Comment by gauravlinux** [comment]
I found a solution it only work in red terminal or sudo terminal

**Comment by gauravlinux** [comment]
It is weird every tool work in normal terminal but this tool specifically
required root terminal
